# Generated by Django 4.0.2 on 2022-02-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_container_alter_watering_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='containers',
            field=models.ManyToManyField(to='main_app.Container'),
        ),
    ]
